# Generated by Django 4.0.3 on 2022-03-21 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topuc',
            new_name='Topic',
        ),
    ]
